// automatically generated by ../../scripts/make-patterns-js.py

var FIELD_EVENTS = [
  "HJ",
  "PV",
  "LJ",
  "TJ",
  "DT",
  "JT",
  "HT",
  "SP",
  "WT",
  "SWT",
  "BT",
  "ST",
  "GDT",
  "OT"
];
var FIELD_SORT_ORDER = [
  "HJ",
  "PV",
  "LJ",
  "TJ",
  "SP",
  "DT",
  "HT",
  "JT",
  "ST",
  "GDT",
  "BT",
  "WT",
  "SWT",
  "OT"
];
var JUMPS = [
  "HJ",
  "PV",
  "LJ",
  "TJ"
];
var MULTI_EVENTS = [
  "BI",
  "TRI",
  "QUAD",
  "PEN",
  "HEX",
  "HEP",
  "OCT",
  "ENN",
  "DEC",
  "HEN",
  "DOD",
  "ICO",
  "PENI",
  "PENWT"
];
var STANDARD_FEMALE_TRACK_EVENTS = [
  "100",
  "200",
  "400",
  "800",
  "1500",
  "5000",
  "10000",
  "100H",
  "400H",
  "3000SC",
  "4x100",
  "4x400"
];
var STANDARD_MALE_TRACK_EVENTS = [
  "100",
  "200",
  "400",
  "800",
  "1500",
  "5000",
  "10000",
  "110H",
  "400H",
  "3000SC",
  "4x100",
  "4x400"
];
var THROWS = [
  "DT",
  "JT",
  "HT",
  "SP",
  "WT",
  "SWT",
  "BT",
  "ST",
  "GDT",
  "OT"
];
var PAT_EVENT_CODE = /^(?:[bB][iI]|[tT][rR][iI]|[qQ][uU][aA][dD]|[pP][eE][nN]|[hH][eE][xX]|[hH][eE][pP]|[oO][cC][tT]|[eE][nN][nN]|[dD][eE][cC]|[hH][eE][nN]|[dD][oO][dD]|[iI][cC][oO]|[pP][eE][nN][iI]|[pP][eE][nN][wW][tT])$|^(?:(?:(\d+)(?:[lLsS]?[hH](?:3[36])?|[yY]|[sS][cC]|[wW])?)|[sS][cC]|[2345][mM][tT]|[lL][hH]|[sS][hH])$|^(?:(?:[mM][iI][lL][eE]|[mM][aA][rR]|[hH][mM])[wW]?|[xX][cC]|(?:\d{1,3}(\.\d\d?)?(?:[MKk]|[MKk][wW]|[wW])))$|^(?:(?:[wW][tT](\d?\d\.?\d*[Kk]|)|[jJ][tT]([45678]00|)|[sS][wW][tT]|[gG][dD][tT]|[bB][tT](?:((?:\d|\d\.\d)[kK]))?|[oO][tT]|[dD][tT](\d\.?\d*[Kk]|)|[hH][tT](\d\.?\d*[Kk]|))|[sS][pP](\d\.?\d*[Kk]|))$|^(?:HJ|PV)$|^(?:LJ|TJ)$|^(?:(\d{1,2})[xX](\d{2,5}[hH]?|[rR][eE][lL][aA][yY]))$|^(?:(\d{2,4})([hH]|[sS][cC]))$|^(?:\d\d?([hH](?:[rR]|[wW])))$/;
var PAT_FIELD = /^(?:(?:[wW][tT](\d?\d\.?\d*[Kk]|)|[jJ][tT]([45678]00|)|[sS][wW][tT]|[gG][dD][tT]|[bB][tT](?:((?:\d|\d\.\d)[kK]))?|[oO][tT]|[dD][tT](\d\.?\d*[Kk]|)|[hH][tT](\d\.?\d*[Kk]|))|[sS][pP](\d\.?\d*[Kk]|))$|^(?:HJ|PV)$|^(?:LJ|TJ)$/;
var PAT_FINISH_RECORD = /^(\d{1,2}:)?(\d{1,2}:)?(\d{1,2})(\.?\d+)?$|^(DNF|DQ|DNS)$/;
var PAT_HORIZONTAL_JUMPS = /^(?:LJ|TJ)$/;
var PAT_HURDLES = /^(?:(\d{2,4})([hH]|[sS][cC]))$/;
var PAT_JUMPS = /^(?:HJ|PV)$|^(?:LJ|TJ)$/;
var PAT_LEADING_DIGITS = /^\d+/;
var PAT_LEADING_FLOAT = /^\d+\.\d*/;
var PAT_LENGTH_EVENT = /^(?:LJ|TJ)$|^(?:(?:[wW][tT](\d?\d\.?\d*[Kk]|)|[jJ][tT]([45678]00|)|[sS][wW][tT]|[gG][dD][tT]|[bB][tT](?:((?:\d|\d\.\d)[kK]))?|[oO][tT]|[dD][tT](\d\.?\d*[Kk]|)|[hH][tT](\d\.?\d*[Kk]|))|[sS][pP](\d\.?\d*[Kk]|))$/;
var PAT_LONG_SECONDS = /^\d{3,6}(\.?\d+)?$/;
var PAT_MULTI = /^(?:[bB][iI]|[tT][rR][iI]|[qQ][uU][aA][dD]|[pP][eE][nN]|[hH][eE][xX]|[hH][eE][pP]|[oO][cC][tT]|[eE][nN][nN]|[dD][eE][cC]|[hH][eE][nN]|[dD][oO][dD]|[iI][cC][oO]|[pP][eE][nN][iI]|[pP][eE][nN][wW][tT])$/;
var PAT_NOT_FINISHED = /^(DNF|DQ|DNS)$/;
var PAT_PERF = /^(\d{1,2}:)?(\d{1,2}:)?(\d{1,2})(\.?\d+)?$/;
var PAT_RACES_FOR_DISTANCE = /^(?:\d\d?([hH](?:[rR]|[wW])))$/;
var PAT_RELAYS = /^(?:(\d{1,2})[xX](\d{2,5}[hH]?|[rR][eE][lL][aA][yY]))$/;
var PAT_ROAD = /^(?:(?:[mM][iI][lL][eE]|[mM][aA][rR]|[hH][mM])[wW]?|[xX][cC]|(?:\d{1,3}(\.\d\d?)?(?:[MKk]|[MKk][wW]|[wW])))$/;
var PAT_RUN = /^(?:(?:(\d+)(?:[lLsS]?[hH](?:3[36])?|[yY]|[sS][cC]|[wW])?)|[sS][cC]|[2345][mM][tT]|[lL][hH]|[sS][hH])$|^(?:(?:[mM][iI][lL][eE]|[mM][aA][rR]|[hH][mM])[wW]?|[xX][cC]|(?:\d{1,3}(\.\d\d?)?(?:[MKk]|[MKk][wW]|[wW])))$/;
var PAT_THROWS = /^(?:(?:[wW][tT](\d?\d\.?\d*[Kk]|)|[jJ][tT]([45678]00|)|[sS][wW][tT]|[gG][dD][tT]|[bB][tT](?:((?:\d|\d\.\d)[kK]))?|[oO][tT]|[dD][tT](\d\.?\d*[Kk]|)|[hH][tT](\d\.?\d*[Kk]|))|[sS][pP](\d\.?\d*[Kk]|))$/;
var PAT_TIMED_EVENT = /^(?:(?:(\d+)(?:[lLsS]?[hH](?:3[36])?|[yY]|[sS][cC]|[wW])?)|[sS][cC]|[2345][mM][tT]|[lL][hH]|[sS][hH])$|^(?:(\d{2,4})([hH]|[sS][cC]))$|^(?:(?:[mM][iI][lL][eE]|[mM][aA][rR]|[hH][mM])[wW]?|[xX][cC]|(?:\d{1,3}(\.\d\d?)?(?:[MKk]|[MKk][wW]|[wW])))$|^(?:(\d{1,2})[xX](\d{2,5}[hH]?|[rR][eE][lL][aA][yY]))$/;
var PAT_TRACK = /^(?:(?:(\d+)(?:[lLsS]?[hH](?:3[36])?|[yY]|[sS][cC]|[wW])?)|[sS][cC]|[2345][mM][tT]|[lL][hH]|[sS][hH])$/;
var PAT_VERTICAL_JUMPS = /^(?:HJ|PV)$/;

module.exports = {
  FIELD_EVENTS,
  FIELD_SORT_ORDER,
  JUMPS,
  MULTI_EVENTS,
  STANDARD_FEMALE_TRACK_EVENTS,
  STANDARD_MALE_TRACK_EVENTS,
  THROWS,
  PAT_EVENT_CODE,
  PAT_FIELD,
  PAT_FINISH_RECORD,
  PAT_HORIZONTAL_JUMPS,
  PAT_HURDLES,
  PAT_JUMPS,
  PAT_LEADING_DIGITS,
  PAT_LEADING_FLOAT,
  PAT_LENGTH_EVENT,
  PAT_LONG_SECONDS,
  PAT_MULTI,
  PAT_NOT_FINISHED,
  PAT_PERF,
  PAT_RACES_FOR_DISTANCE,
  PAT_RELAYS,
  PAT_ROAD,
  PAT_RUN,
  PAT_THROWS,
  PAT_TIMED_EVENT,
  PAT_TRACK,
  PAT_VERTICAL_JUMPS
};
