[project]
name = "athlib"
version = "0.9.6"
authors = [
  { name="Andy Robinson and others", email="andy@opentrack.run" },
]
description = "Utilities for track and field athletics"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

license = {file = "LICENSE"}

[project.urls]
Homepage = "https://github.com/openath/athlib"
Issues = "https://github.com/openath/athlib/issues"

[build-system]
requires = ["setuptools>=82.0"]
build-backend = "setuptools.build_meta"